name: ai_farming_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.3.0  # For API requests
  provider: ^6.0.3  # State management
  image_picker: ^0.8.9  # For uploading images
  flutter_tflite: ^1.0.0  # TensorFlow Lite for AI model integration
  geolocator: ^9.0.2  # GPS location for weather data
  flutter_spinkit: ^5.1.0  # Loading animations
  firebase_core: ^2.3.0  # Firebase integration
  firebase_auth: ^4.1.3  # Authentication
  cloud_firestore: ^4.1.0  # Firestore database

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true