name: ai_farming_app
description: AI Powered Farming Flutter App
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.3.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  geolocator: ^13.0.2
  provider: ^6.0.3
  cloud_firestore: ^5.6.4 # or the latest available
  firebase_auth: ^5.5.0 # or the latest available
  firebase_auth_web: ^5.14.0 # or the latest available
  firebase_core: ^3.12.0 # or the latest available
  flutter_spinkit: ^5.1.0
  permission_handler: ^11.4.0
  flutter_svg: ^2.0.7
  location: ^8.0.0
  tflite_flutter: ^0.11.0
  intl: ^0.19.0 # Or the latest version
  

  

  image: ^4.5.3
  ffi: 2.1.4
  flutter_lints: ^5.0.0
  


  flutter_localizations:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  logger: ^2.5.0
  flutter_cache_manager: ^3.4.1
  fl_chart: ^0.70.2
  flutter_vector_icons: ^2.0.0
  image_picker_for_web: ^3.0.6
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/Poppins-Regular.ttf
    - assets/fonts/Poppins-Bold.ttf
    - assets/.env
    - assets/plant_disease_model_mobilenetv2.tflite
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
